### ISSUE TITLE
When internet is down, integration triggers a re-auth

### ISSUE THREAD

**Issue by mikey0000** [mikey0000/ha-electric-kiwi#2]
Authentication failed while fetching Electric Kiwi HOP Data data: Access token failure: Cannot connect to host account-link.nabucasa.com:443 ssl:default [Try again]

Expected:
Fail and don't trigger re-auth

What happens:
triggers re-auth

**Comment by obrendino** [comment]
Hi Mikey.  I need to reconfigure the integration every few hours as select.hour_of_free_power becomes unavailable.  HA is has an ethernet connection to the internet so unsure if this is the same issue that you have raised.  Other sensors seem to be available and keep the same data.  I use select.hour_of_free_power as  drop down input or through voice command.

**Comment by mikey0000** [comment]
Yeah this is likely a problem with EK, and their auth server, I've tried raising it, maybe an issue on github will raise it, I'll raise it with them there again, I've been in direct contact with both Nabu Casa and EK but things have fallen away on this issue. I'll see if I can stop it from refreshing so often. Unfortunately due to the prod keys being with Nabu it's hard to resolve on my own. I'll see what I can do, I'm suffering too.

**Comment by mikey0000** [comment]
@obrendino can you try now with my latest update, I've reduced the interval for hop updates to 15 minutes as I went back through some old emails and suspect the refresh token expires causing the 500, just made the change now so please give it a go and let me know if this resolves the issue.

**Comment by obrendino** [comment]
Thanks Mikey.  Seems stable now.  Been like that since yesterday arvo and overnight ;)

**Comment by mikey0000** [comment]
I think I've resolved this bug as well in a previous commit. So I'll close for now. Any new issues just open a ticket/issue.
