### ISSUE TITLE
Select entity for HOP has disappeared

### ISSUE THREAD

**Issue by turi400** [mikey0000/ha-electric-kiwi#5]
Updated to 54066ae as a reauth was required. However, after the update the select.hour_of_power entity has disappeared.

**Comment by obrendino** [comment]
I was just going to post the same issue.  Adding that forcing a state change to sensor.hour_of_free_power_start/end does not update within EK.

**Comment by mikey0000** [comment]
Sorry, saw the issue last night but was too tired, also was waiting on the authorization server to be back up and running, will have it fixed this morning.

**Comment by obrendino** [comment]
Awesome, thank you Mikey.

**Comment by mikey0000** [comment]
Fixed and pushed. Will break it on a separate branch next time :D
