### ISSUE TITLE
Oauth page redirected?

### ISSUE THREAD

**Issue by obrendino** [mikey0000/ha-electric-kiwi#6]
Hi Mikey.  Seems EK have redirected their Oauth login to main account login?  Integration is not working.

https://welcome.electrickiwi.co.nz/oauth/authorize?response_type=code&client_id=**************&redirect_uri=https://my.electrickiwi.co.nz/callback&scope=save_customer%20read_session%20read_connection%20read_customer%20read_savings%20read_credits%20save_password%20read_account%20read_billing%20save_billing%20read_hop_connection%20save_payment%20read_payment%20save_url%20read_email%20read_billing_bill_file%20read_subscriptions%20save_subscriptions%20read_hop%20save_hop%20read_refer%20save_refer%20read_contact_reasons%20save_messages%20read_messages%20read_config%20read_notification%20save_notification%20save_connection%20save_device%20read_consumption%20read_nuid%20create_payment_session%20save_payment_details&state=*************&code_challenge=****************&code_challenge_method=S256

**Comment by mikey0000** [comment]
Cool I'll take a look and raise it with electric kiwi

**Comment by mikey0000** [comment]
Resolved now
