### ISSUE TITLE
Hour of free power start and end not correct

### ISSUE THREAD

**Issue by tazomatalax** [mikey0000/ha-electric-kiwi#7]
Hi,

I'm getting the start being 3am and hour end being 4am when the free hour is set to 4pm to 5pm.
It seems to be earlier? is this a UTC thing?

**Comment by mikey0000** [comment]
Yes, I've got a fix for this, I'll push it out now for you.

6/08/2023 10:16:46 am tazomatalax ***@***.***>:

**Comment by mikey0000** [comment]
OK pushed a change, let me know if it fixes it

6/08/2023 10:16:46 am tazomatalax ***@***.***>:

**Comment by tazomatalax** [comment]
Champion, yeah that's perfect!
