### ISSUE TITLE
What CT are you using?

### ISSUE THREAD

**Issue by matthuisman** [mikey0000/ha-electric-kiwi#8]
Hi @mikey0000 ,

Just wondering what your using to measure the house consumption. 

Off the shelf device?
If so, can you please advise what one?
I just got a new home and want to get the power automated

**Comment by mikey0000** [comment]
IoTaWatt, they also have CT recommendations. Let me know if you want more details on CT clamps

18/11/2023 8:34:38 am Matt Huisman ***@***.***>:

**Comment by matthuisman** [comment]
That looks a little overkill for me. Think I'll just get a shelly em with
50a. I just need to do whole house for automated hour of power.

**Comment by mikey0000** [comment]
Normally you use 100A for mains. Though 50A will probably be fine, you need Ref voltage for it to be accurate I believe. If your only after mains.   I'd look for something that will give you an accurate reading. The IoTaWatt for example is OK but it's not super accurate.

19/11/2023 7:48:36 am Matt Huisman ***@***.***>:

> 
> That looks a little overkill for me. Think I'll just get a shelly em with
> 50a. I just need to do whole house for automated hour of power.
>

**Comment by matthuisman** [comment]
Just to select the right hour, I suspect accuracy isn't too crucial. Just
as long as it's consistently inaccurate 😂

They only do 50a or 120a. My mains breaker is 63a. So think 120 the
accuracy might be quite a bit out. I hope I'm never drawing over 50a.

How have you found EK bills? Are you getting pretty close to them on your
usage?

**Comment by mikey0000** [comment]
I haven't checked in a while, I think it's consistently around. .5kw off. So yeah anything that reads current will do fine for setting HOP hour.

19/11/2023 8:35:01 am Matt Huisman ***@***.***>:

> 
> Just to select the right hour, I suspect accuracy isn't too crucial. Just
> as long as it's consistently inaccurate 😂
> 
> They only do 50a or 120a. My mains breaker is 63a. So think 120 the
> accuracy might be quite a bit out. I hope I'm never drawing over 50a.
> 
> How have you found EK bills? Are you getting pretty close to them on your
> usage?
>

**Comment by matthuisman** [comment]
Hi @mikey0000 I've got my power usage steaming into HA now and have installed your EK . Are you able to share your automation for setting the correct HOP each night?

**Comment by mikey0000** [comment]
That's the one thing I haven't managed haha, let me know if you figure it out and I'll add it to a wiki

2/12/2023 4:49:25 pm Matt Huisman ***@***.***>:
